version: '2.0'

services:

  postgres:
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - "./postgres-scripts:/docker-entrypoint-initdb.d"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
