CREATE TABLE IF NOT EXISTS AREA_AGENT_ASSIGNMENTS (
  AID SERIAL PRIMARY KEY,
  ANAME VARCHAR(40) NOT NULL,
  PAID INTEGER,
  HLVL INTEGER NOT NULL,
  AGLNAME VARCHAR(40) NOT NULL,
  AGFNAME VARCHAR(40) NOT NULL,
  AGEML VARCHAR(40) NOT NULL
)